/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Funciones.Contacto;
import Funciones.Directorio;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author pedrodenaro
 * 
 * TODO:
 *      - Create instance of customer with input values
 *      - Add City comboBox functionality
 *      - Check difference between MouseListener and ActionListener
 * 
 */
public class frmAgregarContacto extends javax.swing.JInternalFrame {

    private List<JTextField> textFields;
    private List<JLabel> labels;    
    private Directorio directorio;
    
    /**
     * Creates new form AgregarContactoJFrame
     */
    public frmAgregarContacto(Directorio directorio) {
        this.directorio = directorio;
        this.textFields = new ArrayList<JTextField>();
        initComponents();
        llenarCiudades();

//        // Debe haber una forma de loopear sobre los child items, y quedarnos con los TextField usand isInstance
        textFields.add(TextFieldDNI);
        textFields.add(TextFieldNombre);
        textFields.add(TextFieldApellido);
        textFields.add(TextFieldDomicilio);
        textFields.add(TextFieldTelefono);        
        
    }
    
    private void llenarCiudades(){
        jComboCiudades.removeAllItems();
        Set<String> ciudades = directorio.getCiudadesDisponibles();
        for (String ciudad : ciudades) {
            jComboCiudades.addItem(ciudad);
        }
    }

    private frmAgregarContacto() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPaneErrorDNI = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        TextFieldDNI = new javax.swing.JTextField();
        LabelDNI = new javax.swing.JLabel();
        LabelNombre = new javax.swing.JLabel();
        TextFieldNombre = new javax.swing.JTextField();
        LabelApellido = new javax.swing.JLabel();
        TextFieldApellido = new javax.swing.JTextField();
        LabelCiudad = new javax.swing.JLabel();
        jComboCiudades = new javax.swing.JComboBox<>();
        LabelDomicilio = new javax.swing.JLabel();
        TextFieldDomicilio = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        LabelTelefono = new javax.swing.JLabel();
        TextFieldTelefono = new javax.swing.JTextField();
        ButtonGuardarCliente = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();

        jOptionPaneErrorDNI.setMessage("Debe ingresar valor numérico para DNI");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TextFieldDNI.setName("DNI"); // NOI18N

        LabelDNI.setText("DNI:");

        LabelNombre.setText("Nombre:");

        TextFieldNombre.setName("Nombre"); // NOI18N

        LabelApellido.setText("Apellido");

        TextFieldApellido.setName("Apellido"); // NOI18N

        LabelCiudad.setText("Ciudad");

        jComboCiudades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCiudadesActionPerformed(evt);
            }
        });

        LabelDomicilio.setText("Domicilio");

        TextFieldDomicilio.setName("Domicilio"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNombre)
                    .addComponent(LabelDNI)
                    .addComponent(LabelApellido)
                    .addComponent(LabelCiudad)
                    .addComponent(LabelDomicilio))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextFieldDNI)
                    .addComponent(TextFieldNombre)
                    .addComponent(TextFieldApellido)
                    .addComponent(jComboCiudades, 0, 166, Short.MAX_VALUE)
                    .addComponent(TextFieldDomicilio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombre)
                    .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelApellido)
                    .addComponent(TextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCiudad)
                    .addComponent(jComboCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDomicilio)
                    .addComponent(TextFieldDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelTelefono.setText("Telefono");

        TextFieldTelefono.setName("Telefono"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTelefono)
                .addGap(37, 37, 37)
                .addComponent(TextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTelefono)
                    .addComponent(TextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        ButtonGuardarCliente.setText("Guardar");
        ButtonGuardarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonGuardarClienteMouseClicked(evt);
            }
        });
        ButtonGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGuardarClienteActionPerformed(evt);
            }
        });

        ButtonSalir.setText("Salir");
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(ButtonGuardarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonSalir)
                        .addGap(65, 65, 65)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonGuardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSalir))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGuardarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonGuardarClienteActionPerformed

    private void clearAllTextFields() {
        for (JTextField textField : textFields) {
            textField.setText("");
        }
    }
    
    private void ButtonGuardarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonGuardarClienteMouseClicked

        boolean saveOk = true;
        for (JTextField textField: textFields) {
            if (textField.getText().equals("")) {
                JOptionPane.showMessageDialog(
                    this,
                    "No ingresó ningún valor para el campo " + textField.getName(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                saveOk = false;
                break;
            }
            if (textField.getName().equals("DNI") || 
                    textField.getName().equals("Telefono")) {
                String textValue = textField.getText();
                try {
                    long longValue = Long.parseLong(textValue); // Debemos usar esto para el contacto                
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(
                            this,
                            "Debe ingresar un valor numérico para " + textField.getName(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    textField.setText("");
                    saveOk = false;
                }
            }                       
        }
        if (saveOk) {
            // get text inputs
            long DNI = Long.parseLong(TextFieldDNI.getText());
            String nombre = TextFieldNombre.getText();
            String apellido = TextFieldApellido.getText();
            String ciudad = (String) jComboCiudades.getSelectedItem();
            String domicilio = TextFieldDomicilio.getText();
            long telefono = Long.parseLong(TextFieldTelefono.getText());
            // create contact and add to directorio
            Contacto contacto = new Contacto(DNI, nombre, apellido, ciudad, domicilio);
            directorio.agregarContacto(telefono, contacto);            
            // show msg and clear text inputs
            JOptionPane.showMessageDialog(this, "Client added successfully!");
            clearAllTextFields();
        }
        
    }//GEN-LAST:event_ButtonGuardarClienteMouseClicked

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ButtonSalirActionPerformed

    private void jComboCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCiudadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboCiudadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAgregarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAgregarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAgregarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAgregarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAgregarContacto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonGuardarCliente;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JLabel LabelApellido;
    private javax.swing.JLabel LabelCiudad;
    private javax.swing.JLabel LabelDNI;
    private javax.swing.JLabel LabelDomicilio;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelTelefono;
    private javax.swing.JTextField TextFieldApellido;
    private javax.swing.JTextField TextFieldDNI;
    private javax.swing.JTextField TextFieldDomicilio;
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JTextField TextFieldTelefono;
    private javax.swing.JComboBox<String> jComboCiudades;
    private javax.swing.JOptionPane jOptionPaneErrorDNI;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
